<?php
/**
 * GetClientClientIdAddressesResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Frengky\Fineract
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Apache Fineract
 *
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@fineract.apache.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Frengky\Fineract;

/**
 * GetClientClientIdAddressesResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetClientClientIdAddressesResponse
 * @package     Frengky\Fineract
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetClientClientIdAddressesResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetClientClientIdAddressesResponse"
     */
    public function testGetClientClientIdAddressesResponse()
    {
    }

    /**
     * Test attribute "clientId"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "addressType"
     */
    public function testPropertyAddressType()
    {
    }

    /**
     * Test attribute "addressId"
     */
    public function testPropertyAddressId()
    {
    }

    /**
     * Test attribute "addressTypeId"
     */
    public function testPropertyAddressTypeId()
    {
    }

    /**
     * Test attribute "isActive"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "addressLine1"
     */
    public function testPropertyAddressLine1()
    {
    }

    /**
     * Test attribute "addressLine2"
     */
    public function testPropertyAddressLine2()
    {
    }

    /**
     * Test attribute "addressLine3"
     */
    public function testPropertyAddressLine3()
    {
    }

    /**
     * Test attribute "townVillage"
     */
    public function testPropertyTownVillage()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "countyDistrict"
     */
    public function testPropertyCountyDistrict()
    {
    }

    /**
     * Test attribute "stateProvinceId"
     */
    public function testPropertyStateProvinceId()
    {
    }

    /**
     * Test attribute "countryName"
     */
    public function testPropertyCountryName()
    {
    }

    /**
     * Test attribute "stateName"
     */
    public function testPropertyStateName()
    {
    }

    /**
     * Test attribute "countryId"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "postalCode"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "createdBy"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "updatedBy"
     */
    public function testPropertyUpdatedBy()
    {
    }
}
