<?php
/**
 * GetLoansLoanIdResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Frengky\Fineract
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Apache Fineract
 *
 * Apache Fineract is a secure, multi-tenanted microfinance platform  The goal of the Apache Fineract API is to empower developers to build apps on top of the Apache Fineract Platform<br>The [reference app](https://cui.fineract.dev) (username: mifos, password: password) works on the same demo tenant as the interactive links in this documentation  - The API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) - Find out more about Apache Fineract [here](/fineract-provider/api-docs/apiLive.htm#top) - You can [Try The API From Your Browser](/fineract-provider/api-docs/apiLive.htm#interact) - The Generic Options are available [here](/fineract-provider/api-docs/apiLive.htm#genopts) - Find out more about [Updating Dates and Numbers](/fineract-provider/api-docs/apiLive.htm#dates_and_numbers) - For the Authentication and the Basic of HTTP and HTTPS refer [here](/fineract-provider/api-docs/apiLive.htm#authentication_overview) - Check about ERROR codes [here](/fineract-provider/api-docs/apiLive.htm#errors)  Please refer to the [old documentation](/fineract-provider/api-docs/apiLive.htm) for any documentation queries
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@fineract.apache.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Frengky\Fineract;

/**
 * GetLoansLoanIdResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetLoansLoanIdResponse
 * @package     Frengky\Fineract
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetLoansLoanIdResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetLoansLoanIdResponse"
     */
    public function testGetLoansLoanIdResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "accountNo"
     */
    public function testPropertyAccountNo()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "clientId"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "clientName"
     */
    public function testPropertyClientName()
    {
    }

    /**
     * Test attribute "clientOfficeId"
     */
    public function testPropertyClientOfficeId()
    {
    }

    /**
     * Test attribute "loanProductId"
     */
    public function testPropertyLoanProductId()
    {
    }

    /**
     * Test attribute "loanProductName"
     */
    public function testPropertyLoanProductName()
    {
    }

    /**
     * Test attribute "loanProductDescription"
     */
    public function testPropertyLoanProductDescription()
    {
    }

    /**
     * Test attribute "loanPurposeId"
     */
    public function testPropertyLoanPurposeId()
    {
    }

    /**
     * Test attribute "loanPurposeName"
     */
    public function testPropertyLoanPurposeName()
    {
    }

    /**
     * Test attribute "loanOfficerId"
     */
    public function testPropertyLoanOfficerId()
    {
    }

    /**
     * Test attribute "loanOfficerName"
     */
    public function testPropertyLoanOfficerName()
    {
    }

    /**
     * Test attribute "loanType"
     */
    public function testPropertyLoanType()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "principal"
     */
    public function testPropertyPrincipal()
    {
    }

    /**
     * Test attribute "termFrequency"
     */
    public function testPropertyTermFrequency()
    {
    }

    /**
     * Test attribute "termPeriodFrequencyType"
     */
    public function testPropertyTermPeriodFrequencyType()
    {
    }

    /**
     * Test attribute "numberOfRepayments"
     */
    public function testPropertyNumberOfRepayments()
    {
    }

    /**
     * Test attribute "repaymentEvery"
     */
    public function testPropertyRepaymentEvery()
    {
    }

    /**
     * Test attribute "repaymentFrequencyType"
     */
    public function testPropertyRepaymentFrequencyType()
    {
    }

    /**
     * Test attribute "interestRatePerPeriod"
     */
    public function testPropertyInterestRatePerPeriod()
    {
    }

    /**
     * Test attribute "interestRateFrequencyType"
     */
    public function testPropertyInterestRateFrequencyType()
    {
    }

    /**
     * Test attribute "annualInterestRate"
     */
    public function testPropertyAnnualInterestRate()
    {
    }

    /**
     * Test attribute "amortizationType"
     */
    public function testPropertyAmortizationType()
    {
    }

    /**
     * Test attribute "interestType"
     */
    public function testPropertyInterestType()
    {
    }

    /**
     * Test attribute "interestCalculationPeriodType"
     */
    public function testPropertyInterestCalculationPeriodType()
    {
    }

    /**
     * Test attribute "transactionProcessingStrategyId"
     */
    public function testPropertyTransactionProcessingStrategyId()
    {
    }

    /**
     * Test attribute "timeline"
     */
    public function testPropertyTimeline()
    {
    }

    /**
     * Test attribute "summary"
     */
    public function testPropertySummary()
    {
    }
}
